import { useMemo, useState } from 'react'
import { Icon } from '../components/Icon'
import type { UniversityDetails } from '../api/client'
import type { WorkflowStage } from '../types/domain'

export function UniversityDetailsPage({ data }: { data: UniversityDetails }) {
  const [selectedStageId, setSelectedStageId] = useState(data.workflow.find((s) => s.status === 'active')?.id ?? data.workflow[0]?.id ?? 1)
  const selectedStage = useMemo(() => data.workflow.find((stage) => stage.id === selectedStageId)!, [data.workflow, selectedStageId])
  const { university, workflowStages, programs, activities } = { university: data.university, workflowStages: data.workflow, programs: data.programs, activities: data.activities }

  return <div className="content">
    <div className="page-heading"><div><div className="eyebrow">КАРТОЧКА УЧЕБНОГО ЗАВЕДЕНИЯ</div><div className="title-row"><h1>{university.name}</h1><span className="status-pill"><span />{university.status}</span></div><p className="muted">{university.city} · Контакт: {university.contactPerson}</p></div><button className="primary-button"><Icon name="plus" size={18} /> Добавить задачу</button></div>
    <section className="kpi-grid"><Kpi label="Программы" value={university.programsCount} detail={`${university.activePrograms} активных`} icon="book" /><Kpi label="Обучающиеся" value={university.students.toLocaleString('ru-RU')} detail="за текущий период" icon="users" /><Kpi label="Потоки" value={university.streams} detail="в работе" icon="calendar" /><Kpi label="Прогресс" value={`${university.progress}%`} detail="общий этап взаимодействия" icon="chart" progress={university.progress} /></section>
    <div className="dashboard-grid"><section className="card workflow-card"><div className="card-header"><div><h2>Жизненный цикл взаимодействия</h2><p>14 этапов · текущий этап выделен</p></div><button className="ghost-button">История изменений <Icon name="arrow" size={16} /></button></div><div className="workflow">{workflowStages.map((stage, index) => <button key={stage.id} className={`stage ${stage.status} ${selectedStageId === stage.id ? 'selected' : ''}`} onClick={() => setSelectedStageId(stage.id)}><div className="stage-marker">{stage.status === 'done' ? <Icon name="check" size={14} /> : stage.id}</div><div className="stage-copy"><strong>{stage.shortTitle}</strong>{stage.date && <span>{stage.date}</span>}</div>{index < workflowStages.length - 1 && <div className="stage-line" />}</button>)}</div></section>
      <section className="card stage-detail"><div className="card-header compact"><div><span className="detail-kicker">ВЫБРАННЫЙ ЭТАП</span><h2>{selectedStage.title}</h2></div><button className="more-button"><Icon name="more" size={19} /></button></div><div className="detail-status"><span className={`status-dot ${selectedStage.status}`} />{statusText(selectedStage.status)}</div><div className="detail-row"><span>Ответственный</span><strong>{selectedStage.owner ?? 'Не назначен'}</strong></div><div className="detail-row"><span>Дата начала</span><strong>{selectedStage.date ?? '—'}</strong></div><div className="detail-note"><div className="note-icon"><Icon name="file" size={16} /></div><div><strong>Комментарий</strong><p>{selectedStage.note ?? 'Для этого этапа пока нет комментариев.'}</p></div></div><button className="outline-button">Открыть этап <Icon name="arrow" size={16} /></button></section></div>
    <div className="lower-grid"><section className="card programs-card"><div className="card-header"><div><h2>Образовательные программы</h2><p>Программы этого учебного заведения</p></div><button className="ghost-button">Все программы <Icon name="arrow" size={16} /></button></div><div className="table-wrap"><table><thead><tr><th>Программа</th><th>ИТ-продукт</th><th>Обучающиеся</th><th>Потоки</th><th>Востребованность</th><th>Этап</th></tr></thead><tbody>{programs.map((program) => <tr key={program.id}><td><strong>{program.name}</strong><span className="table-secondary">{program.applications.toLocaleString('ru-RU')} заявок</span></td><td>{program.product}</td><td>{program.students}</td><td>{program.streams}</td><td><div className="demand"><div className="demand-bar"><span style={{ width: `${program.demand}%` }} /></div><strong>{program.demand}%</strong></div></td><td><span className="stage-tag">{program.stage}</span></td></tr>)}</tbody></table></div></section>
      <section className="card activity-card"><div className="card-header"><div><h2>Активность</h2><p>Последние изменения</p></div><button className="more-button"><Icon name="more" size={19} /></button></div><div className="activity-list">{activities.map((activity) => <div className="activity" key={activity.id}><div className={`activity-icon ${activity.type}`}><span /></div><div className="activity-body"><div className="activity-top"><strong>{activity.title}</strong><span>{activity.time}</span></div><p>{activity.description}</p></div></div>)}</div></section></div>
  </div>
}
function Kpi({ label, value, detail, icon, progress }: { label: string; value: string | number; detail: string; icon: 'book' | 'users' | 'calendar' | 'chart'; progress?: number }) { return <div className="kpi card"><div className="kpi-top"><span>{label}</span><div className="kpi-icon"><Icon name={icon} size={18} /></div></div><div className="kpi-value">{value}</div><div className="kpi-detail">{detail}</div>{progress !== undefined && <div className="progress-track"><span style={{ width: `${progress}%` }} /></div>}</div> }
function statusText(status: WorkflowStage['status']) { if (status === 'done') return 'Выполнено'; if (status === 'active') return 'В процессе'; if (status === 'blocked') return 'Требует внимания'; return 'Предстоит' }
